class CreateKarvyfeeds < ActiveRecord::Migration
  def change
    create_table :karvyfeeds do |t|
    	t.string :AMC_CODE
		t.string :BROKE_CD
		t.string :SBBR_CODE
		t.string :USER_CODE
		t.string :USR_TXN_NO
		t.string :APPL_NO
		t.string :FOLIO_NO
		t.string :Ck_DIG_NO
		t.string :TRXN_TYPE
		t.string :SCH_CODE
		t.string :FIRST_NAME
		t.string :JONT_NAME1
		t.string :JONT_NAME2
		t.string :ADD1
		t.string :ADD2
		t.string :ADD3
		t.string :CITY
		t.string :PINCODE
		t.string :PHONE_OFF
		t.string :MOBILE_NO
		t.date :TRXN_DATE
		t.string :TRXN_TIME
		t.float :UNITS
		t.float :AMOUNT
		t.string :CLOS_AC_CH
		t.date :DOB
		t.string :GUARDIAN
		t.string :TAX_NUMBER
		t.string :PHONE_RES
		t.string :FAX_OFF
		t.string :FAX_RES
		t.string :EMAIL
		t.string :ACCT_NO
		t.string :ACCT_TYPE
		t.string :BANK_NAME
		t.string :BR_NAME
		t.string :BANK_CITY
		t.string :REINV_TAG
		t.string :HOLD_NATUR
		t.string :OCC_CODE
		t.string :TAX_STATUS
		t.string :REMARKS
		t.string :STATE
		t.string :PAN_2_HLDR
		t.string :PAN_3_HLDR
		t.string :GUARD_PAN
		t.string :LOCATION
		t.string :UINNO
		t.string :FORM6061
		t.string :FORM6061J1
		t.string :FORM6061J2
		t.string :PAY_MEC
		t.string :RTGS_CD
		t.string :NEFT_CD
		t.string :MICR_CD
		t.string :DEPBANK
		t.string :DEP_ACNO
		t.string :DEP_DATE
		t.string :DEP_RFNo
		t.string :SUB_TRXN_T
		t.string :SIP_RFNO
		t.string :SIP_RGDT
		t.string :NOM_NAME
		t.string :NOM_RELA
		t.string :KYC_FLG
		t.string :POA_STAT
		t.string :MOD_TRXN
		t.string :SIGN_VF
		t.string :CUST_ID
		t.string :LOG_WT
		t.string :LOG_PE
		t.string :DPID
		t.string :CLIENTID
		t.string :NRI_SOF
		t.string :GUARD_RELA
		t.string :PAN_VALI
		t.string :GPAN_VALI
		t.string :J1PAN_VALI
		t.string :J2PAN_VALI
		t.string :NRI_ADD1
		t.string :NRI_ADD2
		t.string :NRI_ADD3
		t.string :NRI_CITY
		t.string :NRI_STATE
		t.string :NRI_COUN
		t.string :NRI_PIN
		t.date :NOM_DOB
		t.string :NOM_PERC
		t.string :NOM_ADD1
		t.string :NOM_ADD2
		t.string :NOM_ADD3
		t.string :NOM_CITY
		t.string :NOM_STATE
		t.string :NOM_COUN
		t.string :NOM_PIN
		t.string :NOM_EMAIL
		t.string :NOM_MOB
		t.string :NOM1_NAME
		t.string :NOM1_RELA
		t.string :NOM1_DOB
		t.string :NOM1_PERC
		t.string :NOM1_ADD1
		t.string :NOM1_ADD2
		t.string :NOM1_ADD3
		t.string :NOM1_CITY
		t.string :NOM1_STATE
		t.string :NOM1_COUN
		t.string :NOM1_PIN
		t.string :NOM1_EMAIL
		t.string :NOM1_MOB
		t.string :NOM2_NAME
		t.string :NOM2_RELA
		t.string :NOM2_DOB
		t.string :NOM2_PERC
		t.string :NOM2_ADD1
		t.string :NOM2_ADD2
		t.string :NOM2_ADD3
		t.string :NOM2_CITY
		t.string :NOM2_STATE
		t.string :NOM2_COUN
		t.string :NOM2_PIN
		t.string :NOM2_EMAIL
		t.string :NOM2_MOB
		t.string :FIRC_STA
		t.string :SIP_STDT
		t.string :SIP_ENDT
		t.string :SIP_NOINST
		t.string :SIP_FREQ
		t.string :EUIN
		t.string :EUIN_OPTIN
		t.string :E1
		t.string :E2
		t.string :E3
		t.string :E4
		t.string :E5
		t.string :E6


      t.timestamps
    end
  end
end
