# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20140421164737) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "banks", force: true do |t|
    t.integer  "user_id"
    t.string   "name_of_bank"
    t.string   "account_num"
    t.string   "account_type"
    t.string   "mode_of_holding"
    t.string   "first_holder"
    t.string   "second_holder"
    t.string   "branch_address"
    t.string   "city"
    t.string   "ifsc_code"
    t.string   "micr_code"
    t.integer  "sip_mandate_status"
    t.integer  "sip_validity"
    t.float    "sip_upper_limit"
    t.string   "umrn"
    t.string   "reason"
    t.string   "bankid_pg"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "cams_data", force: true do |t|
    t.integer  "transaction_id"
    t.text     "sent_feed"
    t.text     "recieved_feed"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "camsfeeds", force: true do |t|
    t.string   "amc_code"
    t.string   "folio_no"
    t.string   "prodcode"
    t.string   "scheme"
    t.string   "inv_name"
    t.string   "trxntype"
    t.string   "trxnno"
    t.string   "trxnmode"
    t.string   "trxnstat"
    t.string   "usercode"
    t.string   "usrtrxno"
    t.date     "traddate"
    t.date     "postdate"
    t.float    "purprice"
    t.float    "units"
    t.float    "amount"
    t.string   "brokcode"
    t.string   "subbrok"
    t.string   "brokperc"
    t.string   "brokcomm"
    t.string   "altfolio"
    t.date     "rep_date"
    t.string   "time1"
    t.string   "trxnsubtyp"
    t.string   "application_no"
    t.string   "trxn_nature"
    t.float    "tax"
    t.float    "total_tax"
    t.string   "te_15h"
    t.string   "micr_no"
    t.string   "remarks"
    t.string   "swflag"
    t.string   "old_folio"
    t.string   "seq_no"
    t.string   "reinvest_flag"
    t.string   "mult_brok"
    t.float    "stt"
    t.string   "location"
    t.string   "scheme_type"
    t.string   "tax_status"
    t.float    "load"
    t.string   "scanrefno"
    t.string   "pan"
    t.float    "inv_iin"
    t.string   "targ_src_scheme"
    t.string   "trxn_type_flag"
    t.string   "ticob_trtype"
    t.string   "ticob_trno"
    t.date     "ticob_posted_date"
    t.string   "dp_id"
    t.float    "trxn_charges"
    t.float    "eligib_amt"
    t.string   "src_of_txn"
    t.string   "trxn_suffix"
    t.string   "siptrxnno"
    t.string   "ter_location"
    t.string   "euin"
    t.string   "euin_valid"
    t.string   "euin_opted"
    t.string   "sub_brk_arn"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "city_masters", force: true do |t|
    t.string   "description"
    t.string   "cams_code"
    t.string   "karvy_code"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "due_transactions", force: true do |t|
    t.integer  "transaction_id"
    t.date     "due_date"
    t.string   "sip_registration_no"
    t.string   "sip_counter"
    t.integer  "sip_installments"
    t.string   "status"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "feeds", force: true do |t|
    t.integer  "transaction_id"
    t.text     "registrar_feed"
    t.text     "registrar_reverse_feed"
    t.text     "pg_feed"
    t.text     "pg_reverse_feed"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "funds", force: true do |t|
    t.string   "amfi_code"
    t.string   "datasource_code"
    t.string   "amc_name"
    t.string   "registrar"
    t.string   "registrar_amc_code"
    t.string   "registrar_scheme_code"
    t.string   "pg_amc_code"
    t.string   "pg_scheme_code"
    t.string   "prodcode"
    t.string   "fund_type"
    t.string   "classification"
    t.string   "scheme_name"
    t.date     "launch_date"
    t.integer  "min_investment"
    t.string   "exit_load"
    t.float    "net_assets"
    t.float    "nav"
    t.string   "category"
    t.float    "expense_ratio"
    t.string   "colour_code"
    t.string   "benchmark"
    t.integer  "min_sip_investment"
    t.integer  "min_sip_chqs"
    t.float    "fund_ytd"
    t.float    "fund_1month"
    t.float    "fund_3month"
    t.float    "fund_1year"
    t.float    "fund_3year"
    t.float    "fund_5year"
    t.float    "fund_10year"
    t.float    "benchmark_ytd"
    t.float    "benchmark_1month"
    t.float    "benchmark_3month"
    t.float    "benchmark_1year"
    t.float    "benchmark_3year"
    t.float    "benchmark_5year"
    t.float    "benchmark_10year"
    t.float    "category_ytd"
    t.float    "category_1month"
    t.float    "category_3month"
    t.float    "category_1year"
    t.float    "category_3year"
    t.float    "category_5year"
    t.float    "category_10year"
    t.integer  "rank_ytd"
    t.integer  "rank_1month"
    t.integer  "rank_3month"
    t.integer  "rank_1year"
    t.integer  "rank_3year"
    t.integer  "rank_5year"
    t.integer  "rank_10year"
    t.integer  "no_of_fund_ytd"
    t.integer  "no_of_fund_1month"
    t.integer  "no_of_fund_3month"
    t.integer  "no_of_fund_1year"
    t.integer  "no_of_fund_3year"
    t.integer  "no_of_fund_5year"
    t.integer  "no_of_fund_10year"
    t.date     "trailing_returns_date"
    t.float    "fund_mean"
    t.float    "fund_stddev"
    t.float    "fund_sharpe"
    t.float    "fund_sortino"
    t.float    "fund_beta"
    t.float    "fund_alpha"
    t.float    "benchmark_mean"
    t.float    "benchmark_stddev"
    t.float    "benchmark_sharpe"
    t.float    "benchmark_sortino"
    t.float    "benchmark_beta"
    t.float    "benchmark_alpha"
    t.float    "category_mean"
    t.float    "category_stddev"
    t.float    "category_sharpe"
    t.float    "category_sortino"
    t.float    "category_beta"
    t.float    "category_alpha"
    t.integer  "rank_mean"
    t.integer  "rank_stddev"
    t.integer  "rank_sharpe"
    t.integer  "rank_sortino"
    t.integer  "rank_beta"
    t.integer  "rank_alpha"
    t.integer  "no_of_fund_mean"
    t.integer  "no_of_fund_stddev"
    t.integer  "no_of_fund_sharpe"
    t.integer  "no_of_fund_sortino"
    t.integer  "no_of_fund_beta"
    t.integer  "no_of_fund_alpha"
    t.date     "risk_measure_date"
    t.string   "no_of_stocks"
    t.float    "top_10_sectors"
    t.float    "top_5_sectors"
    t.float    "top_3_sectors"
    t.float    "portfolio_pb_ratio"
    t.float    "portfolio_pe_ratio"
    t.string   "holdings1_company"
    t.string   "holdings1_sector"
    t.float    "holdings1_pe"
    t.float    "holdings1_asset"
    t.string   "holdings2_company"
    t.string   "holdings2_sector"
    t.float    "holdings2_pe"
    t.float    "holdings2_asset"
    t.string   "holdings3_company"
    t.string   "holdings3_sector"
    t.float    "holdings3_pe"
    t.float    "holdings3_asset"
    t.string   "holdings4_company"
    t.string   "holdings4_sector"
    t.float    "holdings4_pe"
    t.float    "holdings4_asset"
    t.string   "holdings5_company"
    t.string   "holdings5_sector"
    t.float    "holdings5_pe"
    t.float    "holdings5_asset"
    t.string   "holdings6_company"
    t.string   "holdings6_sector"
    t.float    "holdings6_pe"
    t.float    "holdings6_asset"
    t.string   "holdings7_company"
    t.string   "holdings7_sector"
    t.float    "holdings7_pe"
    t.float    "holdings7_asset"
    t.string   "holdings8_company"
    t.string   "holdings8_sector"
    t.float    "holdings8_pe"
    t.float    "holdings8_asset"
    t.string   "holdings9_company"
    t.string   "holdings9_sector"
    t.float    "holdings9_pe"
    t.float    "holdings9_asset"
    t.string   "holdings10_company"
    t.string   "holdings10_sector"
    t.float    "holdings10_pe"
    t.float    "holdings10_asset"
    t.text     "investment_objective"
    t.string   "fund_manager"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "holdings", force: true do |t|
    t.integer  "user_id"
    t.integer  "fund_id"
    t.string   "folio"
    t.float    "units",         default: 0.0
    t.float    "buy_value",     default: 0.0
    t.float    "current_value", default: 0.0
    t.string   "amc"
    t.string   "extra1"
    t.float    "dividend_amt",  default: 0.0
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "karvy_data", force: true do |t|
    t.integer  "transaction_id"
    t.text     "sent_feed"
    t.text     "recieved_feed"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "karvyfeeds", force: true do |t|
    t.string   "AMC_CODE"
    t.string   "BROKE_CD"
    t.string   "SBBR_CODE"
    t.string   "USER_CODE"
    t.string   "USR_TXN_NO"
    t.string   "APPL_NO"
    t.string   "FOLIO_NO"
    t.string   "CK_DIG_NO"
    t.string   "TRXN_TYPE"
    t.string   "SCH_CODE"
    t.string   "FIRST_NAME"
    t.string   "JONT_NAME1"
    t.string   "JONT_NAME2"
    t.string   "ADD1"
    t.string   "ADD2"
    t.string   "ADD3"
    t.string   "CITY"
    t.string   "PINCODE"
    t.string   "PHONE_OFF"
    t.string   "MOBILE_NO"
    t.string   "TRXN_DATE"
    t.string   "TRXN_TIME"
    t.string   "UNITS"
    t.string   "AMOUNT"
    t.string   "CLOS_AC_CH"
    t.string   "DOB"
    t.string   "GUARDIAN"
    t.string   "TAX_NUMBER"
    t.string   "PHONE_RES"
    t.string   "FAX_OFF"
    t.string   "FAX_RES"
    t.string   "EMAIL"
    t.string   "ACCT_NO"
    t.string   "ACCT_TYPE"
    t.string   "BANK_NAME"
    t.string   "BR_NAME"
    t.string   "BANK_CITY"
    t.string   "REINV_TAG"
    t.string   "HOLD_NATUR"
    t.string   "OCC_CODE"
    t.string   "TAX_STATUS"
    t.string   "REMARKS"
    t.string   "STATE"
    t.string   "PAN_2_HLDR"
    t.string   "PAN_3_HLDR"
    t.string   "GUARD_PAN"
    t.string   "LOCATION"
    t.string   "UINNO"
    t.string   "FORM6061"
    t.string   "FORM6061J1"
    t.string   "FORM6061J2"
    t.string   "PAY_MEC"
    t.string   "RTGS_CD"
    t.string   "NEFT_CD"
    t.string   "MICR_CD"
    t.string   "DEPBANK"
    t.string   "DEP_ACNO"
    t.string   "DEP_DATE"
    t.string   "DEP_RFNo"
    t.string   "SUB_TRXN_T"
    t.string   "SIP_RFNO"
    t.string   "SIP_RGDT"
    t.string   "NOM_NAME"
    t.string   "NOM_RELA"
    t.string   "KYC_FLG"
    t.string   "POA_STAT"
    t.string   "MOD_TRXN"
    t.string   "SIGN_VF"
    t.string   "CUST_ID"
    t.string   "LOG_WT"
    t.string   "LOG_PE"
    t.string   "DPID"
    t.string   "CLIENTID"
    t.string   "NRI_SOF"
    t.string   "GUARD_RELA"
    t.string   "PAN_VALI"
    t.string   "GPAN_VALI"
    t.string   "J1PAN_VALI"
    t.string   "J2PAN_VALI"
    t.string   "NRI_ADD1"
    t.string   "NRI_ADD2"
    t.string   "NRI_ADD3"
    t.string   "NRI_CITY"
    t.string   "NRI_STATE"
    t.string   "NRI_COUN"
    t.string   "NRI_PIN"
    t.string   "NOM_DOB"
    t.string   "NOM_PERC"
    t.string   "NOM_ADD1"
    t.string   "NOM_ADD2"
    t.string   "NOM_ADD3"
    t.string   "NOM_CITY"
    t.string   "NOM_STATE"
    t.string   "NOM_COUN"
    t.string   "NOM_PIN"
    t.string   "NOM_EMAIL"
    t.string   "NOM_MOB"
    t.string   "NOM1_NAME"
    t.string   "NOM1_RELA"
    t.string   "NOM1_DOB"
    t.string   "NOM1_PERC"
    t.string   "NOM1_ADD1"
    t.string   "NOM1_ADD2"
    t.string   "NOM1_ADD3"
    t.string   "NOM1_CITY"
    t.string   "NOM1_STATE"
    t.string   "NOM1_COUN"
    t.string   "NOM1_PIN"
    t.string   "NOM1_EMAIL"
    t.string   "NOM1_MOB"
    t.string   "NOM2_NAME"
    t.string   "NOM2_RELA"
    t.string   "NOM2_DOB"
    t.string   "NOM2_PERC"
    t.string   "NOM2_ADD1"
    t.string   "NOM2_ADD2"
    t.string   "NOM2_ADD3"
    t.string   "NOM2_CITY"
    t.string   "NOM2_STATE"
    t.string   "NOM2_COUN"
    t.string   "NOM2_PIN"
    t.string   "NOM2_EMAIL"
    t.string   "NOM2_MOB"
    t.string   "FIRC_STA"
    t.string   "SIP_STDT"
    t.string   "SIP_ENDT"
    t.string   "SIP_NOINST"
    t.string   "SIP_FREQ"
    t.string   "EUIN"
    t.string   "EUIN_OPTIN"
    t.string   "E1"
    t.string   "E2"
    t.string   "E3"
    t.string   "E4"
    t.string   "E5"
    t.string   "E6"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "kycs", force: true do |t|
    t.integer  "user_id"
    t.string   "holding_priority"
    t.string   "first_name"
    t.string   "last_name"
    t.string   "father_spouse_name"
    t.string   "gender"
    t.string   "marital_status"
    t.date     "date_of_birth"
    t.string   "nationality"
    t.string   "residence_status"
    t.string   "pan"
    t.string   "proof_of_identity"
    t.string   "c_house_no"
    t.string   "c_street_name"
    t.string   "c_area_name"
    t.string   "c_city_town_village"
    t.string   "c_state"
    t.string   "c_country"
    t.string   "c_postal_code"
    t.string   "c_landline"
    t.string   "c_mobile"
    t.string   "c_email"
    t.string   "c_proof_of_address"
    t.boolean  "same"
    t.string   "p_house_no"
    t.string   "p_street_name"
    t.string   "p_area_name"
    t.string   "p_city_town_village"
    t.string   "p_state"
    t.string   "p_country"
    t.string   "p_postal_code"
    t.string   "p_landline"
    t.string   "p_mobile"
    t.string   "p_email"
    t.string   "p_proof_of_address"
    t.float    "annual_income"
    t.string   "occupation"
    t.string   "pep_status"
    t.string   "nominee_name"
    t.string   "nominee_relation"
    t.string   "nominee_address"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "part_validation"
    t.date     "nominee_dob"
    t.string   "nominee_gaurdian"
    t.string   "nominee_minor_flag"
    t.boolean  "nominee_flag"
  end

  create_table "occupation_masters", force: true do |t|
    t.string   "description"
    t.string   "cams_code"
    t.string   "karvy_code"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "pgfeeds", force: true do |t|
    t.integer  "user_id"
    t.string   "order_number"
    t.float    "amount"
    t.text     "msgtopg"
    t.text     "msgfrompg"
    t.string   "error_status"
    t.string   "error_desc"
    t.string   "auth_status"
    t.string   "payement_status"
    t.string   "transaction_ref_no"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "state_masters", force: true do |t|
    t.string   "description"
    t.string   "cams_code"
    t.string   "karvy_code"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "tax_status_master", force: true do |t|
    t.integer  "transaction_id"
    t.text     "sent_feed"
    t.text     "recieved_feed"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "tax_status_masters", force: true do |t|
    t.string   "description"
    t.string   "cams_code"
    t.string   "karvy_code"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "transactions", force: true do |t|
    t.integer  "user_id"
    t.integer  "bank_id"
    t.integer  "fund_id"
    t.string   "tr_id"
    t.string   "reinvestment_tag"
    t.string   "tr_type"
    t.string   "tr_mode"
    t.float    "amount"
    t.float    "units"
    t.float    "price_per_unit"
    t.date     "tr_date"
    t.date     "date"
    t.date     "sip_start_date"
    t.string   "sip_registration_no"
    t.string   "sip_frequency"
    t.integer  "sip_installments"
    t.integer  "sip_installment_count"
    t.string   "folio_id"
    t.string   "registrar"
    t.string   "registrar_tr_status"
    t.string   "registrar_tr_status_reason"
    t.string   "pg_tr_status"
    t.string   "pg_tr_status_reason"
    t.string   "checksum"
    t.string   "liq_non"
    t.string   "error_status"
    t.string   "error_desc"
    t.string   "auth_status"
    t.float    "transaction_charges"
    t.string   "euin_status"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "pg_order_number"
    t.string   "pg_transaction_no"
  end

  create_table "users", force: true do |t|
    t.string   "name"
    t.string   "email",                  default: "",    null: false
    t.string   "encrypted_password",     default: "",    null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          default: 0,     null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string   "current_sign_in_ip"
    t.string   "last_sign_in_ip"
    t.boolean  "admin",                  default: false
    t.integer  "kyc_status",             default: 1
    t.integer  "bank_status",            default: 1
    t.string   "pg_user_code"
    t.string   "karvy_user_code"
    t.string   "cams_user_code"
    t.string   "ft_user_code"
    t.string   "bnp_user_code"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "confirmation_token"
    t.datetime "confirmed_at"
    t.datetime "confirmation_sent_at"
    t.integer  "tax_status"
    t.string   "holding_type"
    t.string   "unique_session_id"
  end

  add_index "users", ["confirmation_token"], name: "index_users_on_confirmation_token", unique: true, using: :btree
  add_index "users", ["email"], name: "index_users_on_email", unique: true, using: :btree
  add_index "users", ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true, using: :btree

end
