class CreateFunds < ActiveRecord::Migration
  def change
    create_table :funds do |t|
      t.string :amfi_code
	  t.string :datasource_code	
      t.string :amc_name
      t.string :registrar
	  t.string :registrar_amc_code
	  t.string :registrar_scheme_code
	  t.string :pg_amc_code
	  t.string :pg_scheme_code
	  t.string :prodcode
	  t.string :fund_type
      t.string :scheme_name
      t.date :launch_date
      t.integer :min_investment
      t.string :exit_load
      t.float :net_assets
      t.float :nav
      t.string :category
      t.float :expense_ratio
      t.string :colour_code
      t.string :benchmark
      t.integer :min_sip_investment
      t.integer :min_sip_chqs
      t.float :fund_ytd
      t.float :fund_1month
      t.float :fund_3month
      t.float :fund_1year
      t.float :fund_3year
      t.float :fund_5year
      t.float :fund_10year
      t.float :benchmark_ytd
      t.float :benchmark_1month
      t.float :benchmark_3month
      t.float :benchmark_1year
      t.float :benchmark_3year
      t.float :benchmark_5year
      t.float :benchmark_10year
      t.float :category_ytd
      t.float :category_1month
      t.float :category_3month
      t.float :category_1year
      t.float :category_3year
      t.float :category_5year
      t.float :category_10year
      t.integer :rank_ytd
      t.integer :rank_1month
      t.integer :rank_3month
      t.integer :rank_1year
      t.integer :rank_3year
      t.integer :rank_5year
      t.integer :rank_10year
      t.integer :no_of_fund_ytd
      t.integer :no_of_fund_1month
      t.integer :no_of_fund_3month
      t.integer :no_of_fund_1year
      t.integer :no_of_fund_3year
      t.integer :no_of_fund_5year
      t.integer :no_of_fund_10year
      t.date :trailing_returns_date
      t.float :fund_mean
      t.float :fund_stddev
      t.float :fund_sharpe
      t.float :fund_sortino
      t.float :fund_beta
      t.float :fund_alpha
      t.float :benchmark_mean
      t.float :benchmark_stddev
      t.float :benchmark_sharpe
      t.float :benchmark_sortino
      t.float :benchmark_beta
      t.float :benchmark_alpha
      t.float :category_mean
      t.float :category_stddev
      t.float :category_sharpe
      t.float :category_sortino
      t.float :category_beta
      t.float :category_alpha
      t.integer :rank_mean
      t.integer :rank_stddev
      t.integer :rank_sharpe
      t.integer :rank_sortino
      t.integer :rank_beta
      t.integer :rank_alpha
      t.integer :no_of_fund_mean
      t.integer :no_of_fund_stddev
      t.integer :no_of_fund_sharpe
      t.integer :no_of_fund_sortino
      t.integer :no_of_fund_beta
      t.integer :no_of_fund_alpha
      t.date :risk_measure_date
      t.string :no_of_stocks
      t.float :top_10_sectors
      t.float :top_5_sectors
      t.float :top_3_sectors
      t.float :portfolio_pb_ratio
      t.float :portfolio_pe_ratio
      t.string :holdings1_company
      t.string :holdings1_sector
      t.float :holdings1_pe
      t.float :holdings1_asset
      t.string :holdings2_company
      t.string :holdings2_sector
      t.float :holdings2_pe
      t.float :holdings2_asset
      t.string :holdings3_company
      t.string :holdings3_sector
      t.float :holdings3_pe
      t.float :holdings3_asset
      t.string :holdings4_company
      t.string :holdings4_sector
      t.float :holdings4_pe
      t.float :holdings4_asset
      t.string :holdings5_company
      t.string :holdings5_sector
      t.float :holdings5_pe
      t.float :holdings5_asset
      t.string :holdings6_company
      t.string :holdings6_sector
      t.float :holdings6_pe
      t.float :holdings6_asset
      t.string :holdings7_company
      t.string :holdings7_sector
      t.float :holdings7_pe
      t.float :holdings7_asset
      t.string :holdings8_company
      t.string :holdings8_sector
      t.float :holdings8_pe
      t.float :holdings8_asset
      t.string :holdings9_company
      t.string :holdings9_sector
      t.float :holdings9_pe
      t.float :holdings9_asset
      t.string :holdings10_company
      t.string :holdings10_sector
      t.float :holdings10_pe
      t.float :holdings10_asset
      t.text :investment_objective
      t.string :fund_manager

      t.timestamps
    end
  end
end
